language: go
go:
  - 1.5.4
  - 1.6.3
  - 1.7.1
  - tip
os:
  - linux
  - osx
install:
  - go get -v github.com/zquestz/visago
script:
  - go build
  - go fmt ./...
  - go vet ./...
  - go test -i -race ./...
  - go test -v -race ./...
after_script:
  - if [ "$TRAVIS_GO_VERSION" = "1.7.1" ] && [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_TAG" != "" ]; then go get github.com/mitchellh/gox; fi
  - if [ "$TRAVIS_GO_VERSION" = "1.7.1" ] && [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_TAG" != "" ]; then go get github.com/tcnksm/ghr; fi
  - if [ "$TRAVIS_GO_VERSION" = "1.7.1" ] && [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$TRAVIS_TAG" != "" ]; then make compile; ghr --username zquestz --token $GITHUB_TOKEN --replace $TRAVIS_TAG pkg/; fi
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3d90d9e9722a5e2be2d9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
